/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.AccountAsset;
import io.trxplorer.model.tables.records.AccountAssetRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountAssetDao extends DAOImpl<AccountAssetRecord, io.trxplorer.model.tables.pojos.AccountAsset, ULong> {

    /**
     * Create a new AccountAssetDao without any configuration
     */
    public AccountAssetDao() {
        super(AccountAsset.ACCOUNT_ASSET, io.trxplorer.model.tables.pojos.AccountAsset.class);
    }

    /**
     * Create a new AccountAssetDao with an attached configuration
     */
    public AccountAssetDao(Configuration configuration) {
        super(AccountAsset.ACCOUNT_ASSET, io.trxplorer.model.tables.pojos.AccountAsset.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.AccountAsset object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.AccountAsset> fetchById(ULong... values) {
        return fetch(AccountAsset.ACCOUNT_ASSET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.AccountAsset fetchOneById(ULong value) {
        return fetchOne(AccountAsset.ACCOUNT_ASSET.ID, value);
    }

    /**
     * Fetch records that have <code>asset_name IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.AccountAsset> fetchByAssetName(String... values) {
        return fetch(AccountAsset.ACCOUNT_ASSET.ASSET_NAME, values);
    }

    /**
     * Fetch records that have <code>balance IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.AccountAsset> fetchByBalance(ULong... values) {
        return fetch(AccountAsset.ACCOUNT_ASSET.BALANCE, values);
    }

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.AccountAsset> fetchByAccountId(ULong... values) {
        return fetch(AccountAsset.ACCOUNT_ASSET.ACCOUNT_ID, values);
    }
}
