/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.ContractWitnessCreate;
import io.trxplorer.model.tables.records.ContractWitnessCreateRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractWitnessCreateDao extends DAOImpl<ContractWitnessCreateRecord, io.trxplorer.model.tables.pojos.ContractWitnessCreate, UInteger> {

    /**
     * Create a new ContractWitnessCreateDao without any configuration
     */
    public ContractWitnessCreateDao() {
        super(ContractWitnessCreate.CONTRACT_WITNESS_CREATE, io.trxplorer.model.tables.pojos.ContractWitnessCreate.class);
    }

    /**
     * Create a new ContractWitnessCreateDao with an attached configuration
     */
    public ContractWitnessCreateDao(Configuration configuration) {
        super(ContractWitnessCreate.CONTRACT_WITNESS_CREATE, io.trxplorer.model.tables.pojos.ContractWitnessCreate.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(io.trxplorer.model.tables.pojos.ContractWitnessCreate object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractWitnessCreate> fetchById(UInteger... values) {
        return fetch(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.ContractWitnessCreate fetchOneById(UInteger value) {
        return fetchOne(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.ID, value);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractWitnessCreate> fetchByOwnerId(ULong... values) {
        return fetch(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.OWNER_ID, values);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractWitnessCreate> fetchByOwnerAddress(String... values) {
        return fetch(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractWitnessCreate> fetchByUrl(String... values) {
        return fetch(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.URL, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractWitnessCreate> fetchByTransactionId(ULong... values) {
        return fetch(ContractWitnessCreate.CONTRACT_WITNESS_CREATE.TRANSACTION_ID, values);
    }
}
