/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.ContractTransfer;
import io.trxplorer.model.tables.records.ContractTransferRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractTransferDao extends DAOImpl<ContractTransferRecord, io.trxplorer.model.tables.pojos.ContractTransfer, ULong> {

    /**
     * Create a new ContractTransferDao without any configuration
     */
    public ContractTransferDao() {
        super(ContractTransfer.CONTRACT_TRANSFER, io.trxplorer.model.tables.pojos.ContractTransfer.class);
    }

    /**
     * Create a new ContractTransferDao with an attached configuration
     */
    public ContractTransferDao(Configuration configuration) {
        super(ContractTransfer.CONTRACT_TRANSFER, io.trxplorer.model.tables.pojos.ContractTransfer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.ContractTransfer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchById(ULong... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.ContractTransfer fetchOneById(ULong value) {
        return fetchOne(ContractTransfer.CONTRACT_TRANSFER.ID, value);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByOwnerId(ULong... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.OWNER_ID, values);
    }

    /**
     * Fetch records that have <code>to_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByToId(ULong... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.TO_ID, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByAmount(ULong... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByTransactionId(ULong... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.TRANSACTION_ID, values);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByOwnerAddress(String... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>to_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractTransfer> fetchByToAddress(String... values) {
        return fetch(ContractTransfer.CONTRACT_TRANSFER.TO_ADDRESS, values);
    }
}
