/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.ContractFreezeBalance;
import io.trxplorer.model.tables.records.ContractFreezeBalanceRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractFreezeBalanceDao extends DAOImpl<ContractFreezeBalanceRecord, io.trxplorer.model.tables.pojos.ContractFreezeBalance, ULong> {

    /**
     * Create a new ContractFreezeBalanceDao without any configuration
     */
    public ContractFreezeBalanceDao() {
        super(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE, io.trxplorer.model.tables.pojos.ContractFreezeBalance.class);
    }

    /**
     * Create a new ContractFreezeBalanceDao with an attached configuration
     */
    public ContractFreezeBalanceDao(Configuration configuration) {
        super(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE, io.trxplorer.model.tables.pojos.ContractFreezeBalance.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.ContractFreezeBalance object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchById(ULong... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.ContractFreezeBalance fetchOneById(ULong value) {
        return fetchOne(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.ID, value);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchByOwnerAddress(String... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>frozen_balance IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchByFrozenBalance(ULong... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.FROZEN_BALANCE, values);
    }

    /**
     * Fetch records that have <code>frozen_duration IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchByFrozenDuration(ULong... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.FROZEN_DURATION, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchByTransactionId(ULong... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.TRANSACTION_ID, values);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractFreezeBalance> fetchByOwnerId(ULong... values) {
        return fetch(ContractFreezeBalance.CONTRACT_FREEZE_BALANCE.OWNER_ID, values);
    }
}
