/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.ContractUnfreezeBalance;
import io.trxplorer.model.tables.records.ContractUnfreezeBalanceRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractUnfreezeBalanceDao extends DAOImpl<ContractUnfreezeBalanceRecord, io.trxplorer.model.tables.pojos.ContractUnfreezeBalance, ULong> {

    /**
     * Create a new ContractUnfreezeBalanceDao without any configuration
     */
    public ContractUnfreezeBalanceDao() {
        super(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE, io.trxplorer.model.tables.pojos.ContractUnfreezeBalance.class);
    }

    /**
     * Create a new ContractUnfreezeBalanceDao with an attached configuration
     */
    public ContractUnfreezeBalanceDao(Configuration configuration) {
        super(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE, io.trxplorer.model.tables.pojos.ContractUnfreezeBalance.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.ContractUnfreezeBalance object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractUnfreezeBalance> fetchById(ULong... values) {
        return fetch(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.ContractUnfreezeBalance fetchOneById(ULong value) {
        return fetchOne(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE.ID, value);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractUnfreezeBalance> fetchByOwnerAddress(String... values) {
        return fetch(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractUnfreezeBalance> fetchByTransactionId(ULong... values) {
        return fetch(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE.TRANSACTION_ID, values);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractUnfreezeBalance> fetchByOwnerId(ULong... values) {
        return fetch(ContractUnfreezeBalance.CONTRACT_UNFREEZE_BALANCE.OWNER_ID, values);
    }
}
