/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.ContractParticipateAssetIssue;
import io.trxplorer.model.tables.records.ContractParticipateAssetIssueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractParticipateAssetIssueDao extends DAOImpl<ContractParticipateAssetIssueRecord, io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue, ULong> {

    /**
     * Create a new ContractParticipateAssetIssueDao without any configuration
     */
    public ContractParticipateAssetIssueDao() {
        super(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE, io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue.class);
    }

    /**
     * Create a new ContractParticipateAssetIssueDao with an attached configuration
     */
    public ContractParticipateAssetIssueDao(Configuration configuration) {
        super(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE, io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchById(ULong... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue fetchOneById(ULong value) {
        return fetchOne(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.ID, value);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByOwnerId(ULong... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.OWNER_ID, values);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByOwnerAddress(String... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>to_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByToId(ULong... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TO_ID, values);
    }

    /**
     * Fetch records that have <code>to_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByToAddress(String... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TO_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>asset_name IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByAssetName(String... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.ASSET_NAME, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByAmount(ULong... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.ContractParticipateAssetIssue> fetchByTransactionId(ULong... values) {
        return fetch(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TRANSACTION_ID, values);
    }
}
