/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.Market;
import io.trxplorer.model.tables.records.MarketRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketDao extends DAOImpl<MarketRecord, io.trxplorer.model.tables.pojos.Market, UInteger> {

    /**
     * Create a new MarketDao without any configuration
     */
    public MarketDao() {
        super(Market.MARKET, io.trxplorer.model.tables.pojos.Market.class);
    }

    /**
     * Create a new MarketDao with an attached configuration
     */
    public MarketDao(Configuration configuration) {
        super(Market.MARKET, io.trxplorer.model.tables.pojos.Market.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(io.trxplorer.model.tables.pojos.Market object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchById(UInteger... values) {
        return fetch(Market.MARKET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.Market fetchOneById(UInteger value) {
        return fetchOne(Market.MARKET.ID, value);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchBySource(String... values) {
        return fetch(Market.MARKET.SOURCE, values);
    }

    /**
     * Fetch records that have <code>pair IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByPair(String... values) {
        return fetch(Market.MARKET.PAIR, values);
    }

    /**
     * Fetch records that have <code>volume_24h IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByVolume_24h(UInteger... values) {
        return fetch(Market.MARKET.VOLUME_24H, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByPrice(BigDecimal... values) {
        return fetch(Market.MARKET.PRICE, values);
    }

    /**
     * Fetch records that have <code>day IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByDay(Integer... values) {
        return fetch(Market.MARKET.DAY, values);
    }

    /**
     * Fetch records that have <code>month IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByMonth(Integer... values) {
        return fetch(Market.MARKET.MONTH, values);
    }

    /**
     * Fetch records that have <code>year IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByYear(Integer... values) {
        return fetch(Market.MARKET.YEAR, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Market> fetchByLastUpdate(Timestamp... values) {
        return fetch(Market.MARKET.LAST_UPDATE, values);
    }
}
