/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.Transfer;
import io.trxplorer.model.tables.records.TransferRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferDao extends DAOImpl<TransferRecord, io.trxplorer.model.tables.pojos.Transfer, ULong> {

    /**
     * Create a new TransferDao without any configuration
     */
    public TransferDao() {
        super(Transfer.TRANSFER, io.trxplorer.model.tables.pojos.Transfer.class);
    }

    /**
     * Create a new TransferDao with an attached configuration
     */
    public TransferDao(Configuration configuration) {
        super(Transfer.TRANSFER, io.trxplorer.model.tables.pojos.Transfer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.Transfer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchById(ULong... values) {
        return fetch(Transfer.TRANSFER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.Transfer fetchOneById(ULong value) {
        return fetchOne(Transfer.TRANSFER.ID, value);
    }

    /**
     * Fetch records that have <code>from IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByFrom(String... values) {
        return fetch(Transfer.TRANSFER.FROM, values);
    }

    /**
     * Fetch records that have <code>to IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByTo(String... values) {
        return fetch(Transfer.TRANSFER.TO, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByAmount(ULong... values) {
        return fetch(Transfer.TRANSFER.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByToken(String... values) {
        return fetch(Transfer.TRANSFER.TOKEN, values);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByTimestamp(Timestamp... values) {
        return fetch(Transfer.TRANSFER.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Transfer> fetchByTransactionId(ULong... values) {
        return fetch(Transfer.TRANSFER.TRANSACTION_ID, values);
    }
}
