/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.TransactionResult;
import io.trxplorer.model.tables.records.TransactionResultRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionResultDao extends DAOImpl<TransactionResultRecord, io.trxplorer.model.tables.pojos.TransactionResult, ULong> {

    /**
     * Create a new TransactionResultDao without any configuration
     */
    public TransactionResultDao() {
        super(TransactionResult.TRANSACTION_RESULT, io.trxplorer.model.tables.pojos.TransactionResult.class);
    }

    /**
     * Create a new TransactionResultDao with an attached configuration
     */
    public TransactionResultDao(Configuration configuration) {
        super(TransactionResult.TRANSACTION_RESULT, io.trxplorer.model.tables.pojos.TransactionResult.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.TransactionResult object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.TransactionResult> fetchById(ULong... values) {
        return fetch(TransactionResult.TRANSACTION_RESULT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.TransactionResult fetchOneById(ULong value) {
        return fetchOne(TransactionResult.TRANSACTION_RESULT.ID, value);
    }

    /**
     * Fetch records that have <code>fee IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.TransactionResult> fetchByFee(ULong... values) {
        return fetch(TransactionResult.TRANSACTION_RESULT.FEE, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.TransactionResult> fetchByCode(UByte... values) {
        return fetch(TransactionResult.TRANSACTION_RESULT.CODE, values);
    }

    /**
     * Fetch records that have <code>transaction_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.TransactionResult> fetchByTransactionId(ULong... values) {
        return fetch(TransactionResult.TRANSACTION_RESULT.TRANSACTION_ID, values);
    }
}
