/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.VotingRoundStats;
import io.trxplorer.model.tables.records.VotingRoundStatsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotingRoundStatsDao extends DAOImpl<VotingRoundStatsRecord, io.trxplorer.model.tables.pojos.VotingRoundStats, UInteger> {

    /**
     * Create a new VotingRoundStatsDao without any configuration
     */
    public VotingRoundStatsDao() {
        super(VotingRoundStats.VOTING_ROUND_STATS, io.trxplorer.model.tables.pojos.VotingRoundStats.class);
    }

    /**
     * Create a new VotingRoundStatsDao with an attached configuration
     */
    public VotingRoundStatsDao(Configuration configuration) {
        super(VotingRoundStats.VOTING_ROUND_STATS, io.trxplorer.model.tables.pojos.VotingRoundStats.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(io.trxplorer.model.tables.pojos.VotingRoundStats object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchById(UInteger... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.VotingRoundStats fetchOneById(UInteger value) {
        return fetchOne(VotingRoundStats.VOTING_ROUND_STATS.ID, value);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchByAddress(String... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>voting_round_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchByVotingRoundId(UInteger... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.VOTING_ROUND_ID, values);
    }

    /**
     * Fetch records that have <code>vote_count IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchByVoteCount(ULong... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.VOTE_COUNT, values);
    }

    /**
     * Fetch records that have <code>position IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchByPosition(UInteger... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.POSITION, values);
    }

    /**
     * Fetch records that have <code>vote_lost_count IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundStats> fetchByVoteLostCount(ULong... values) {
        return fetch(VotingRoundStats.VOTING_ROUND_STATS.VOTE_LOST_COUNT, values);
    }
}
