/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.VotingRoundVote;
import io.trxplorer.model.tables.records.VotingRoundVoteRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotingRoundVoteDao extends DAOImpl<VotingRoundVoteRecord, io.trxplorer.model.tables.pojos.VotingRoundVote, ULong> {

    /**
     * Create a new VotingRoundVoteDao without any configuration
     */
    public VotingRoundVoteDao() {
        super(VotingRoundVote.VOTING_ROUND_VOTE, io.trxplorer.model.tables.pojos.VotingRoundVote.class);
    }

    /**
     * Create a new VotingRoundVoteDao with an attached configuration
     */
    public VotingRoundVoteDao(Configuration configuration) {
        super(VotingRoundVote.VOTING_ROUND_VOTE, io.trxplorer.model.tables.pojos.VotingRoundVote.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.VotingRoundVote object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchById(ULong... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.VotingRoundVote fetchOneById(ULong value) {
        return fetchOne(VotingRoundVote.VOTING_ROUND_VOTE.ID, value);
    }

    /**
     * Fetch records that have <code>voting_round_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchByVotingRoundId(UInteger... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.VOTING_ROUND_ID, values);
    }

    /**
     * Fetch records that have <code>owner_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchByOwnerAddress(String... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.OWNER_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>vote_address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchByVoteAddress(String... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.VOTE_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>vote_count IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchByVoteCount(Long... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.VOTE_COUNT, values);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.VotingRoundVote> fetchByTimestamp(Timestamp... values) {
        return fetch(VotingRoundVote.VOTING_ROUND_VOTE.TIMESTAMP, values);
    }
}
