/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.daos;


import io.trxplorer.model.tables.Witness;
import io.trxplorer.model.tables.records.WitnessRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WitnessDao extends DAOImpl<WitnessRecord, io.trxplorer.model.tables.pojos.Witness, ULong> {

    /**
     * Create a new WitnessDao without any configuration
     */
    public WitnessDao() {
        super(Witness.WITNESS, io.trxplorer.model.tables.pojos.Witness.class);
    }

    /**
     * Create a new WitnessDao with an attached configuration
     */
    public WitnessDao(Configuration configuration) {
        super(Witness.WITNESS, io.trxplorer.model.tables.pojos.Witness.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(io.trxplorer.model.tables.pojos.Witness object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchById(ULong... values) {
        return fetch(Witness.WITNESS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public io.trxplorer.model.tables.pojos.Witness fetchOneById(ULong value) {
        return fetchOne(Witness.WITNESS.ID, value);
    }

    /**
     * Fetch records that have <code>vote_count IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByVoteCount(ULong... values) {
        return fetch(Witness.WITNESS.VOTE_COUNT, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByUrl(String... values) {
        return fetch(Witness.WITNESS.URL, values);
    }

    /**
     * Fetch records that have <code>total_produced IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByTotalProduced(ULong... values) {
        return fetch(Witness.WITNESS.TOTAL_PRODUCED, values);
    }

    /**
     * Fetch records that have <code>total_missed IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByTotalMissed(ULong... values) {
        return fetch(Witness.WITNESS.TOTAL_MISSED, values);
    }

    /**
     * Fetch records that have <code>latest_block_num IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByLatestBlockNum(ULong... values) {
        return fetch(Witness.WITNESS.LATEST_BLOCK_NUM, values);
    }

    /**
     * Fetch records that have <code>latest_slot_num IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByLatestSlotNum(Long... values) {
        return fetch(Witness.WITNESS.LATEST_SLOT_NUM, values);
    }

    /**
     * Fetch records that have <code>isJobs IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByIsjobs(Byte... values) {
        return fetch(Witness.WITNESS.ISJOBS, values);
    }

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByAccountId(ULong... values) {
        return fetch(Witness.WITNESS.ACCOUNT_ID, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<io.trxplorer.model.tables.pojos.Witness> fetchByAddress(String... values) {
        return fetch(Witness.WITNESS.ADDRESS, values);
    }
}
