/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractVoteWitnessRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractVoteWitness extends TableImpl<ContractVoteWitnessRecord> {

    private static final long serialVersionUID = 561427833;

    /**
     * The reference instance of <code>tmp.contract_vote_witness</code>
     */
    public static final ContractVoteWitness CONTRACT_VOTE_WITNESS = new ContractVoteWitness();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractVoteWitnessRecord> getRecordType() {
        return ContractVoteWitnessRecord.class;
    }

    /**
     * The column <code>tmp.contract_vote_witness.id</code>.
     */
    public final TableField<ContractVoteWitnessRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness.owner_id</code>.
     */
    public final TableField<ContractVoteWitnessRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_vote_witness.owner_address</code>.
     */
    public final TableField<ContractVoteWitnessRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness.vote_address</code>.
     */
    public final TableField<ContractVoteWitnessRecord, String> VOTE_ADDRESS = createField("vote_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness.vote_count</code>.
     */
    public final TableField<ContractVoteWitnessRecord, ULong> VOTE_COUNT = createField("vote_count", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness.support</code>.
     */
    public final TableField<ContractVoteWitnessRecord, UByte> SUPPORT = createField("support", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness.transaction_id</code>.
     */
    public final TableField<ContractVoteWitnessRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_vote_witness</code> table reference
     */
    public ContractVoteWitness() {
        this("contract_vote_witness", null);
    }

    /**
     * Create an aliased <code>tmp.contract_vote_witness</code> table reference
     */
    public ContractVoteWitness(String alias) {
        this(alias, CONTRACT_VOTE_WITNESS);
    }

    private ContractVoteWitness(String alias, Table<ContractVoteWitnessRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractVoteWitness(String alias, Table<ContractVoteWitnessRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractVoteWitnessRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_VOTE_WITNESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractVoteWitnessRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_VOTE_WITNESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractVoteWitnessRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractVoteWitnessRecord>>asList(Keys.KEY_CONTRACT_VOTE_WITNESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractVoteWitnessRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractVoteWitnessRecord, ?>>asList(Keys.FK_CONTRACT_VOTE_WITNESS_OWNER_ID, Keys.FK_CONTRACT_VOTE_WITNESS_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitness as(String alias) {
        return new ContractVoteWitness(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractVoteWitness rename(String name) {
        return new ContractVoteWitness(name, null);
    }
}
