/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractAccountCreateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractAccountCreate extends TableImpl<ContractAccountCreateRecord> {

    private static final long serialVersionUID = 1812071923;

    /**
     * The reference instance of <code>tmp.contract_account_create</code>
     */
    public static final ContractAccountCreate CONTRACT_ACCOUNT_CREATE = new ContractAccountCreate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractAccountCreateRecord> getRecordType() {
        return ContractAccountCreateRecord.class;
    }

    /**
     * The column <code>tmp.contract_account_create.id</code>.
     */
    public final TableField<ContractAccountCreateRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_account_create.account_name</code>.
     */
    public final TableField<ContractAccountCreateRecord, String> ACCOUNT_NAME = createField("account_name", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * The column <code>tmp.contract_account_create.owner_id</code>.
     */
    public final TableField<ContractAccountCreateRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_account_create.transaction_id</code>.
     */
    public final TableField<ContractAccountCreateRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_account_create.owner_address</code>.
     */
    public final TableField<ContractAccountCreateRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_account_create</code> table reference
     */
    public ContractAccountCreate() {
        this("contract_account_create", null);
    }

    /**
     * Create an aliased <code>tmp.contract_account_create</code> table reference
     */
    public ContractAccountCreate(String alias) {
        this(alias, CONTRACT_ACCOUNT_CREATE);
    }

    private ContractAccountCreate(String alias, Table<ContractAccountCreateRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractAccountCreate(String alias, Table<ContractAccountCreateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractAccountCreateRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_ACCOUNT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractAccountCreateRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_ACCOUNT_CREATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractAccountCreateRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractAccountCreateRecord>>asList(Keys.KEY_CONTRACT_ACCOUNT_CREATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractAccountCreateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractAccountCreateRecord, ?>>asList(Keys.FK_CONTRACT_ACCOUNT_CREATE_OWNER_ID, Keys.FK_CONTRACT_ACCOUNT_CREATE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountCreate as(String alias) {
        return new ContractAccountCreate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractAccountCreate rename(String name) {
        return new ContractAccountCreate(name, null);
    }
}
