/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractTransferRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractTransfer extends TableImpl<ContractTransferRecord> {

    private static final long serialVersionUID = -1209484862;

    /**
     * The reference instance of <code>tmp.contract_transfer</code>
     */
    public static final ContractTransfer CONTRACT_TRANSFER = new ContractTransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractTransferRecord> getRecordType() {
        return ContractTransferRecord.class;
    }

    /**
     * The column <code>tmp.contract_transfer.id</code>.
     */
    public final TableField<ContractTransferRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_transfer.owner_id</code>.
     */
    public final TableField<ContractTransferRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_transfer.to_id</code>.
     */
    public final TableField<ContractTransferRecord, ULong> TO_ID = createField("to_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_transfer.amount</code>.
     */
    public final TableField<ContractTransferRecord, ULong> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_transfer.transaction_id</code>.
     */
    public final TableField<ContractTransferRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_transfer.owner_address</code>.
     */
    public final TableField<ContractTransferRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_transfer.to_address</code>.
     */
    public final TableField<ContractTransferRecord, String> TO_ADDRESS = createField("to_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_transfer</code> table reference
     */
    public ContractTransfer() {
        this("contract_transfer", null);
    }

    /**
     * Create an aliased <code>tmp.contract_transfer</code> table reference
     */
    public ContractTransfer(String alias) {
        this(alias, CONTRACT_TRANSFER);
    }

    private ContractTransfer(String alias, Table<ContractTransferRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractTransfer(String alias, Table<ContractTransferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractTransferRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_TRANSFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractTransferRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_TRANSFER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractTransferRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractTransferRecord>>asList(Keys.KEY_CONTRACT_TRANSFER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractTransferRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractTransferRecord, ?>>asList(Keys.FK_CONTRACT_TRANSFER_OWNER_ID, Keys.FK_CONTRACT_TRANSFER_TO_ID, Keys.FK_CONTRACT_TRANSFER_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransfer as(String alias) {
        return new ContractTransfer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractTransfer rename(String name) {
        return new ContractTransfer(name, null);
    }
}
