/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractVoteWitnessMviewRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractVoteWitnessMview extends TableImpl<ContractVoteWitnessMviewRecord> {

    private static final long serialVersionUID = 2080819526;

    /**
     * The reference instance of <code>tmp.contract_vote_witness_mview</code>
     */
    public static final ContractVoteWitnessMview CONTRACT_VOTE_WITNESS_MVIEW = new ContractVoteWitnessMview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractVoteWitnessMviewRecord> getRecordType() {
        return ContractVoteWitnessMviewRecord.class;
    }

    /**
     * The column <code>tmp.contract_vote_witness_mview.id</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.owner_id</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.owner_address</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.vote_address</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, String> VOTE_ADDRESS = createField("vote_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.vote_count</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, ULong> VOTE_COUNT = createField("vote_count", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.support</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, UByte> SUPPORT = createField("support", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_vote_witness_mview.transaction_id</code>.
     */
    public final TableField<ContractVoteWitnessMviewRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_vote_witness_mview</code> table reference
     */
    public ContractVoteWitnessMview() {
        this("contract_vote_witness_mview", null);
    }

    /**
     * Create an aliased <code>tmp.contract_vote_witness_mview</code> table reference
     */
    public ContractVoteWitnessMview(String alias) {
        this(alias, CONTRACT_VOTE_WITNESS_MVIEW);
    }

    private ContractVoteWitnessMview(String alias, Table<ContractVoteWitnessMviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractVoteWitnessMview(String alias, Table<ContractVoteWitnessMviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMview as(String alias) {
        return new ContractVoteWitnessMview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractVoteWitnessMview rename(String name) {
        return new ContractVoteWitnessMview(name, null);
    }
}
