/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractUnfreezeBalanceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractUnfreezeBalance extends TableImpl<ContractUnfreezeBalanceRecord> {

    private static final long serialVersionUID = -810975852;

    /**
     * The reference instance of <code>tmp.contract_unfreeze_balance</code>
     */
    public static final ContractUnfreezeBalance CONTRACT_UNFREEZE_BALANCE = new ContractUnfreezeBalance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractUnfreezeBalanceRecord> getRecordType() {
        return ContractUnfreezeBalanceRecord.class;
    }

    /**
     * The column <code>tmp.contract_unfreeze_balance.id</code>.
     */
    public final TableField<ContractUnfreezeBalanceRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_unfreeze_balance.owner_address</code>.
     */
    public final TableField<ContractUnfreezeBalanceRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_unfreeze_balance.transaction_id</code>.
     */
    public final TableField<ContractUnfreezeBalanceRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_unfreeze_balance.owner_id</code>.
     */
    public final TableField<ContractUnfreezeBalanceRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * Create a <code>tmp.contract_unfreeze_balance</code> table reference
     */
    public ContractUnfreezeBalance() {
        this("contract_unfreeze_balance", null);
    }

    /**
     * Create an aliased <code>tmp.contract_unfreeze_balance</code> table reference
     */
    public ContractUnfreezeBalance(String alias) {
        this(alias, CONTRACT_UNFREEZE_BALANCE);
    }

    private ContractUnfreezeBalance(String alias, Table<ContractUnfreezeBalanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractUnfreezeBalance(String alias, Table<ContractUnfreezeBalanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractUnfreezeBalanceRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_UNFREEZE_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractUnfreezeBalanceRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_UNFREEZE_BALANCE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractUnfreezeBalanceRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractUnfreezeBalanceRecord>>asList(Keys.KEY_CONTRACT_UNFREEZE_BALANCE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractUnfreezeBalanceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractUnfreezeBalanceRecord, ?>>asList(Keys.FK_CONTRACT_UNFREEZE_BALANCE_TX_ID, Keys.FK_CONTRACT_UNFREEZE_BALANCE_OWNER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractUnfreezeBalance as(String alias) {
        return new ContractUnfreezeBalance(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractUnfreezeBalance rename(String name) {
        return new ContractUnfreezeBalance(name, null);
    }
}
