/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractWitnessUpdateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractWitnessUpdate extends TableImpl<ContractWitnessUpdateRecord> {

    private static final long serialVersionUID = 1709514330;

    /**
     * The reference instance of <code>tmp.contract_witness_update</code>
     */
    public static final ContractWitnessUpdate CONTRACT_WITNESS_UPDATE = new ContractWitnessUpdate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractWitnessUpdateRecord> getRecordType() {
        return ContractWitnessUpdateRecord.class;
    }

    /**
     * The column <code>tmp.contract_witness_update.id</code>.
     */
    public final TableField<ContractWitnessUpdateRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_witness_update.update_url</code>.
     */
    public final TableField<ContractWitnessUpdateRecord, String> UPDATE_URL = createField("update_url", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * The column <code>tmp.contract_witness_update.owner_id</code>.
     */
    public final TableField<ContractWitnessUpdateRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_witness_update.owner_address</code>.
     */
    public final TableField<ContractWitnessUpdateRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_witness_update.transaction_id</code>.
     */
    public final TableField<ContractWitnessUpdateRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_witness_update</code> table reference
     */
    public ContractWitnessUpdate() {
        this("contract_witness_update", null);
    }

    /**
     * Create an aliased <code>tmp.contract_witness_update</code> table reference
     */
    public ContractWitnessUpdate(String alias) {
        this(alias, CONTRACT_WITNESS_UPDATE);
    }

    private ContractWitnessUpdate(String alias, Table<ContractWitnessUpdateRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractWitnessUpdate(String alias, Table<ContractWitnessUpdateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractWitnessUpdateRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_WITNESS_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractWitnessUpdateRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_WITNESS_UPDATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractWitnessUpdateRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractWitnessUpdateRecord>>asList(Keys.KEY_CONTRACT_WITNESS_UPDATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractWitnessUpdateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractWitnessUpdateRecord, ?>>asList(Keys.FK_CONTRACT_WITNESS_UPDATE_OWNER_ID, Keys.FK_CONTRACT_WITNESS_UPDATE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdate as(String alias) {
        return new ContractWitnessUpdate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractWitnessUpdate rename(String name) {
        return new ContractWitnessUpdate(name, null);
    }
}
