/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractAssetIssueRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractAssetIssue extends TableImpl<ContractAssetIssueRecord> {

    private static final long serialVersionUID = 1367124769;

    /**
     * The reference instance of <code>tmp.contract_asset_issue</code>
     */
    public static final ContractAssetIssue CONTRACT_ASSET_ISSUE = new ContractAssetIssue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractAssetIssueRecord> getRecordType() {
        return ContractAssetIssueRecord.class;
    }

    /**
     * The column <code>tmp.contract_asset_issue.id</code>.
     */
    public final TableField<ContractAssetIssueRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.owner_id</code>.
     */
    public final TableField<ContractAssetIssueRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_asset_issue.owner_address</code>.
     */
    public final TableField<ContractAssetIssueRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.name</code>.
     */
    public final TableField<ContractAssetIssueRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.total_supply</code>.
     */
    public final TableField<ContractAssetIssueRecord, ULong> TOTAL_SUPPLY = createField("total_supply", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.trx_num</code>.
     */
    public final TableField<ContractAssetIssueRecord, UInteger> TRX_NUM = createField("trx_num", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.num</code>.
     */
    public final TableField<ContractAssetIssueRecord, UInteger> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.start_time</code>.
     */
    public final TableField<ContractAssetIssueRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.end_time</code>.
     */
    public final TableField<ContractAssetIssueRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>tmp.contract_asset_issue.decay_ratio</code>.
     */
    public final TableField<ContractAssetIssueRecord, UInteger> DECAY_RATIO = createField("decay_ratio", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_asset_issue.vote_score</code>.
     */
    public final TableField<ContractAssetIssueRecord, Integer> VOTE_SCORE = createField("vote_score", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tmp.contract_asset_issue.description</code>.
     */
    public final TableField<ContractAssetIssueRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(750), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.url</code>.
     */
    public final TableField<ContractAssetIssueRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.transaction_id</code>.
     */
    public final TableField<ContractAssetIssueRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_asset_issue.abbr</code>.
     */
    public final TableField<ContractAssetIssueRecord, String> ABBR = createField("abbr", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * Create a <code>tmp.contract_asset_issue</code> table reference
     */
    public ContractAssetIssue() {
        this("contract_asset_issue", null);
    }

    /**
     * Create an aliased <code>tmp.contract_asset_issue</code> table reference
     */
    public ContractAssetIssue(String alias) {
        this(alias, CONTRACT_ASSET_ISSUE);
    }

    private ContractAssetIssue(String alias, Table<ContractAssetIssueRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractAssetIssue(String alias, Table<ContractAssetIssueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractAssetIssueRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_ASSET_ISSUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractAssetIssueRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_ASSET_ISSUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractAssetIssueRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractAssetIssueRecord>>asList(Keys.KEY_CONTRACT_ASSET_ISSUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractAssetIssueRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractAssetIssueRecord, ?>>asList(Keys.FK_CONTRACT_ASSET_ISSUE_OWNER_ID, Keys.FK_CONTRACT_ASSET_ISSUE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAssetIssue as(String alias) {
        return new ContractAssetIssue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractAssetIssue rename(String name) {
        return new ContractAssetIssue(name, null);
    }
}
