/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractParticipateAssetIssueRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractParticipateAssetIssue extends TableImpl<ContractParticipateAssetIssueRecord> {

    private static final long serialVersionUID = -806591467;

    /**
     * The reference instance of <code>tmp.contract_participate_asset_issue</code>
     */
    public static final ContractParticipateAssetIssue CONTRACT_PARTICIPATE_ASSET_ISSUE = new ContractParticipateAssetIssue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractParticipateAssetIssueRecord> getRecordType() {
        return ContractParticipateAssetIssueRecord.class;
    }

    /**
     * The column <code>tmp.contract_participate_asset_issue.id</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.owner_id</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.owner_address</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.to_id</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, ULong> TO_ID = createField("to_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.to_address</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, String> TO_ADDRESS = createField("to_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.asset_name</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, String> ASSET_NAME = createField("asset_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.amount</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, ULong> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_participate_asset_issue.transaction_id</code>.
     */
    public final TableField<ContractParticipateAssetIssueRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_participate_asset_issue</code> table reference
     */
    public ContractParticipateAssetIssue() {
        this("contract_participate_asset_issue", null);
    }

    /**
     * Create an aliased <code>tmp.contract_participate_asset_issue</code> table reference
     */
    public ContractParticipateAssetIssue(String alias) {
        this(alias, CONTRACT_PARTICIPATE_ASSET_ISSUE);
    }

    private ContractParticipateAssetIssue(String alias, Table<ContractParticipateAssetIssueRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractParticipateAssetIssue(String alias, Table<ContractParticipateAssetIssueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractParticipateAssetIssueRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_PARTICIPATE_ASSET_ISSUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractParticipateAssetIssueRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_PARTICIPATE_ASSET_ISSUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractParticipateAssetIssueRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractParticipateAssetIssueRecord>>asList(Keys.KEY_CONTRACT_PARTICIPATE_ASSET_ISSUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractParticipateAssetIssueRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractParticipateAssetIssueRecord, ?>>asList(Keys.FK_CONTRACT_PARTICIPATE_ASSET_ISSUE_OWNER_ID, Keys.FK_CONTRACT_PARTICIPATE_ASSET_ISSUE_TO_ID, Keys.FK_CONTRACT_PARTICIPATE_ASSET_ISSUE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssue as(String alias) {
        return new ContractParticipateAssetIssue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractParticipateAssetIssue rename(String name) {
        return new ContractParticipateAssetIssue(name, null);
    }
}
