/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables;


import io.trxplorer.model.Keys;
import io.trxplorer.model.Tmp;
import io.trxplorer.model.tables.records.ContractWitnessCreateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractWitnessCreate extends TableImpl<ContractWitnessCreateRecord> {

    private static final long serialVersionUID = -1323710748;

    /**
     * The reference instance of <code>tmp.contract_witness_create</code>
     */
    public static final ContractWitnessCreate CONTRACT_WITNESS_CREATE = new ContractWitnessCreate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractWitnessCreateRecord> getRecordType() {
        return ContractWitnessCreateRecord.class;
    }

    /**
     * The column <code>tmp.contract_witness_create.id</code>.
     */
    public final TableField<ContractWitnessCreateRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_witness_create.owner_id</code>.
     */
    public final TableField<ContractWitnessCreateRecord, ULong> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>tmp.contract_witness_create.owner_address</code>.
     */
    public final TableField<ContractWitnessCreateRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_witness_create.url</code>.
     */
    public final TableField<ContractWitnessCreateRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * The column <code>tmp.contract_witness_create.transaction_id</code>.
     */
    public final TableField<ContractWitnessCreateRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_witness_create</code> table reference
     */
    public ContractWitnessCreate() {
        this("contract_witness_create", null);
    }

    /**
     * Create an aliased <code>tmp.contract_witness_create</code> table reference
     */
    public ContractWitnessCreate(String alias) {
        this(alias, CONTRACT_WITNESS_CREATE);
    }

    private ContractWitnessCreate(String alias, Table<ContractWitnessCreateRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractWitnessCreate(String alias, Table<ContractWitnessCreateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractWitnessCreateRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_CONTRACT_WITNESS_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractWitnessCreateRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_WITNESS_CREATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractWitnessCreateRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractWitnessCreateRecord>>asList(Keys.KEY_CONTRACT_WITNESS_CREATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractWitnessCreateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractWitnessCreateRecord, ?>>asList(Keys.FK_CONTRACT_WITNESS_CREATE_OWNER_ID, Keys.FK_CONTRACT_WITNESS_CREATE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessCreate as(String alias) {
        return new ContractWitnessCreate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractWitnessCreate rename(String name) {
        return new ContractWitnessCreate(name, null);
    }
}
