/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.AccountAsset;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountAssetRecord extends UpdatableRecordImpl<AccountAssetRecord> implements Record4<ULong, String, ULong, ULong> {

    private static final long serialVersionUID = 2135618023;

    /**
     * Setter for <code>tmp.account_asset.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.account_asset.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.account_asset.asset_name</code>.
     */
    public void setAssetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.account_asset.asset_name</code>.
     */
    public String getAssetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tmp.account_asset.balance</code>.
     */
    public void setBalance(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.account_asset.balance</code>.
     */
    public ULong getBalance() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>tmp.account_asset.account_id</code>.
     */
    public void setAccountId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.account_asset.account_id</code>.
     */
    public ULong getAccountId() {
        return (ULong) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, ULong, ULong> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, ULong, ULong> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return AccountAsset.ACCOUNT_ASSET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AccountAsset.ACCOUNT_ASSET.ASSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return AccountAsset.ACCOUNT_ASSET.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return AccountAsset.ACCOUNT_ASSET.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountAssetRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountAssetRecord value2(String value) {
        setAssetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountAssetRecord value3(ULong value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountAssetRecord value4(ULong value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountAssetRecord values(ULong value1, String value2, ULong value3, ULong value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountAssetRecord
     */
    public AccountAssetRecord() {
        super(AccountAsset.ACCOUNT_ASSET);
    }

    /**
     * Create a detached, initialised AccountAssetRecord
     */
    public AccountAssetRecord(ULong id, String assetName, ULong balance, ULong accountId) {
        super(AccountAsset.ACCOUNT_ASSET);

        set(0, id);
        set(1, assetName);
        set(2, balance);
        set(3, accountId);
    }
}
