/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.BlockResync;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlockResyncRecord extends UpdatableRecordImpl<BlockResyncRecord> implements Record1<ULong> {

    private static final long serialVersionUID = 1284915973;

    /**
     * Setter for <code>tmp.block_resync.num</code>.
     */
    public void setNum(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.block_resync.num</code>.
     */
    public ULong getNum() {
        return (ULong) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<ULong> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<ULong> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return BlockResync.BLOCK_RESYNC.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockResyncRecord value1(ULong value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockResyncRecord values(ULong value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlockResyncRecord
     */
    public BlockResyncRecord() {
        super(BlockResync.BLOCK_RESYNC);
    }

    /**
     * Create a detached, initialised BlockResyncRecord
     */
    public BlockResyncRecord(ULong num) {
        super(BlockResync.BLOCK_RESYNC);

        set(0, num);
    }
}
