/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractParticipateAssetIssue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractParticipateAssetIssueRecord extends UpdatableRecordImpl<ContractParticipateAssetIssueRecord> implements Record8<ULong, ULong, String, ULong, String, String, ULong, ULong> {

    private static final long serialVersionUID = 1874382932;

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.to_id</code>.
     */
    public void setToId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.to_id</code>.
     */
    public ULong getToId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.to_address</code>.
     */
    public void setToAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.to_address</code>.
     */
    public String getToAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.asset_name</code>.
     */
    public void setAssetName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.asset_name</code>.
     */
    public String getAssetName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.amount</code>.
     */
    public void setAmount(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.amount</code>.
     */
    public ULong getAmount() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>tmp.contract_participate_asset_issue.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>tmp.contract_participate_asset_issue.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, ULong, String, ULong, String, String, ULong, ULong> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, ULong, String, ULong, String, String, ULong, ULong> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TO_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.ASSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field8() {
        return ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getToId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getToAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value8() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value2(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value3(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value4(ULong value) {
        setToId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value5(String value) {
        setToAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value6(String value) {
        setAssetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value7(ULong value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord value8(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractParticipateAssetIssueRecord values(ULong value1, ULong value2, String value3, ULong value4, String value5, String value6, ULong value7, ULong value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractParticipateAssetIssueRecord
     */
    public ContractParticipateAssetIssueRecord() {
        super(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE);
    }

    /**
     * Create a detached, initialised ContractParticipateAssetIssueRecord
     */
    public ContractParticipateAssetIssueRecord(ULong id, ULong ownerId, String ownerAddress, ULong toId, String toAddress, String assetName, ULong amount, ULong transactionId) {
        super(ContractParticipateAssetIssue.CONTRACT_PARTICIPATE_ASSET_ISSUE);

        set(0, id);
        set(1, ownerId);
        set(2, ownerAddress);
        set(3, toId);
        set(4, toAddress);
        set(5, assetName);
        set(6, amount);
        set(7, transactionId);
    }
}
