/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractAccountUpdate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractAccountUpdateRecord extends UpdatableRecordImpl<ContractAccountUpdateRecord> implements Record5<ULong, String, ULong, ULong, String> {

    private static final long serialVersionUID = -1361758111;

    /**
     * Setter for <code>tmp.contract_account_update.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_account_update.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_account_update.account_name</code>.
     */
    public void setAccountName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_account_update.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tmp.contract_account_update.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_account_update.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>tmp.contract_account_update.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_account_update.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>tmp.contract_account_update.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_account_update.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, ULong, ULong, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, ULong, ULong, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE.ACCOUNT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord value2(String value) {
        setAccountName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord value3(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord value4(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord value5(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAccountUpdateRecord values(ULong value1, String value2, ULong value3, ULong value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractAccountUpdateRecord
     */
    public ContractAccountUpdateRecord() {
        super(ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE);
    }

    /**
     * Create a detached, initialised ContractAccountUpdateRecord
     */
    public ContractAccountUpdateRecord(ULong id, String accountName, ULong ownerId, ULong transactionId, String ownerAddress) {
        super(ContractAccountUpdate.CONTRACT_ACCOUNT_UPDATE);

        set(0, id);
        set(1, accountName);
        set(2, ownerId);
        set(3, transactionId);
        set(4, ownerAddress);
    }
}
