/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractVoteWitnessMview;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractVoteWitnessMviewRecord extends TableRecordImpl<ContractVoteWitnessMviewRecord> implements Record7<ULong, ULong, String, String, ULong, UByte, ULong> {

    private static final long serialVersionUID = 1449648152;

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.vote_address</code>.
     */
    public void setVoteAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.vote_address</code>.
     */
    public String getVoteAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.vote_count</code>.
     */
    public void setVoteCount(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.vote_count</code>.
     */
    public ULong getVoteCount() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.support</code>.
     */
    public void setSupport(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.support</code>.
     */
    public UByte getSupport() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>tmp.contract_vote_witness_mview.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>tmp.contract_vote_witness_mview.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, ULong, String, String, ULong, UByte, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, ULong, String, String, ULong, UByte, ULong> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.VOTE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.VOTE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.SUPPORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getVoteAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getVoteCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getSupport();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value2(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value3(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value4(String value) {
        setVoteAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value5(ULong value) {
        setVoteCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value6(UByte value) {
        setSupport(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord value7(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractVoteWitnessMviewRecord values(ULong value1, ULong value2, String value3, String value4, ULong value5, UByte value6, ULong value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractVoteWitnessMviewRecord
     */
    public ContractVoteWitnessMviewRecord() {
        super(ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW);
    }

    /**
     * Create a detached, initialised ContractVoteWitnessMviewRecord
     */
    public ContractVoteWitnessMviewRecord(ULong id, ULong ownerId, String ownerAddress, String voteAddress, ULong voteCount, UByte support, ULong transactionId) {
        super(ContractVoteWitnessMview.CONTRACT_VOTE_WITNESS_MVIEW);

        set(0, id);
        set(1, ownerId);
        set(2, ownerAddress);
        set(3, voteAddress);
        set(4, voteCount);
        set(5, support);
        set(6, transactionId);
    }
}
