/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractWitnessUpdate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractWitnessUpdateRecord extends UpdatableRecordImpl<ContractWitnessUpdateRecord> implements Record5<ULong, String, ULong, String, ULong> {

    private static final long serialVersionUID = 1476218601;

    /**
     * Setter for <code>tmp.contract_witness_update.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_witness_update.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_witness_update.update_url</code>.
     */
    public void setUpdateUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_witness_update.update_url</code>.
     */
    public String getUpdateUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tmp.contract_witness_update.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_witness_update.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>tmp.contract_witness_update.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_witness_update.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tmp.contract_witness_update.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_witness_update.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, ULong, String, ULong> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, ULong, String, ULong> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE.UPDATE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUpdateUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord value2(String value) {
        setUpdateUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord value3(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord value4(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord value5(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractWitnessUpdateRecord values(ULong value1, String value2, ULong value3, String value4, ULong value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractWitnessUpdateRecord
     */
    public ContractWitnessUpdateRecord() {
        super(ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE);
    }

    /**
     * Create a detached, initialised ContractWitnessUpdateRecord
     */
    public ContractWitnessUpdateRecord(ULong id, String updateUrl, ULong ownerId, String ownerAddress, ULong transactionId) {
        super(ContractWitnessUpdate.CONTRACT_WITNESS_UPDATE);

        set(0, id);
        set(1, updateUrl);
        set(2, ownerId);
        set(3, ownerAddress);
        set(4, transactionId);
    }
}
