/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractTransfer;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractTransferRecord extends UpdatableRecordImpl<ContractTransferRecord> implements Record7<ULong, ULong, ULong, ULong, ULong, String, String> {

    private static final long serialVersionUID = -1513401118;

    /**
     * Setter for <code>tmp.contract_transfer.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_transfer.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>tmp.contract_transfer.to_id</code>.
     */
    public void setToId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.to_id</code>.
     */
    public ULong getToId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>tmp.contract_transfer.amount</code>.
     */
    public void setAmount(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.amount</code>.
     */
    public ULong getAmount() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>tmp.contract_transfer.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>tmp.contract_transfer.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tmp.contract_transfer.to_address</code>.
     */
    public void setToAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer.to_address</code>.
     */
    public String getToAddress() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, ULong, ULong, ULong, ULong, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, ULong, ULong, ULong, ULong, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractTransfer.CONTRACT_TRANSFER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return ContractTransfer.CONTRACT_TRANSFER.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return ContractTransfer.CONTRACT_TRANSFER.TO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return ContractTransfer.CONTRACT_TRANSFER.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return ContractTransfer.CONTRACT_TRANSFER.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ContractTransfer.CONTRACT_TRANSFER.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ContractTransfer.CONTRACT_TRANSFER.TO_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getToId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getToAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value2(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value3(ULong value) {
        setToId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value4(ULong value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value5(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value6(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord value7(String value) {
        setToAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractTransferRecord
     */
    public ContractTransferRecord() {
        super(ContractTransfer.CONTRACT_TRANSFER);
    }

    /**
     * Create a detached, initialised ContractTransferRecord
     */
    public ContractTransferRecord(ULong id, ULong ownerId, ULong toId, ULong amount, ULong transactionId, String ownerAddress, String toAddress) {
        super(ContractTransfer.CONTRACT_TRANSFER);

        set(0, id);
        set(1, ownerId);
        set(2, toId);
        set(3, amount);
        set(4, transactionId);
        set(5, ownerAddress);
        set(6, toAddress);
    }
}
