/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.ContractTransferAsset;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractTransferAssetRecord extends UpdatableRecordImpl<ContractTransferAssetRecord> implements Record8<ULong, String, ULong, ULong, String, String, ULong, ULong> {

    private static final long serialVersionUID = 131129132;

    /**
     * Setter for <code>tmp.contract_transfer_asset.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.asset_name</code>.
     */
    public void setAssetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.asset_name</code>.
     */
    public String getAssetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.to_id</code>.
     */
    public void setToId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.to_id</code>.
     */
    public ULong getToId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.owner_address</code>.
     */
    public void setOwnerAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.owner_address</code>.
     */
    public String getOwnerAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.to_address</code>.
     */
    public void setToAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.to_address</code>.
     */
    public String getToAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.amount</code>.
     */
    public void setAmount(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.amount</code>.
     */
    public ULong getAmount() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>tmp.contract_transfer_asset.transaction_id</code>.
     */
    public void setTransactionId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>tmp.contract_transfer_asset.transaction_id</code>.
     */
    public ULong getTransactionId() {
        return (ULong) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, String, ULong, ULong, String, String, ULong, ULong> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, String, ULong, ULong, String, String, ULong, ULong> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.ASSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.TO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.OWNER_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.TO_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field8() {
        return ContractTransferAsset.CONTRACT_TRANSFER_ASSET.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getToId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getToAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value8() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value2(String value) {
        setAssetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value3(ULong value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value4(ULong value) {
        setToId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value5(String value) {
        setOwnerAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value6(String value) {
        setToAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value7(ULong value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord value8(ULong value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractTransferAssetRecord values(ULong value1, String value2, ULong value3, ULong value4, String value5, String value6, ULong value7, ULong value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractTransferAssetRecord
     */
    public ContractTransferAssetRecord() {
        super(ContractTransferAsset.CONTRACT_TRANSFER_ASSET);
    }

    /**
     * Create a detached, initialised ContractTransferAssetRecord
     */
    public ContractTransferAssetRecord(ULong id, String assetName, ULong ownerId, ULong toId, String ownerAddress, String toAddress, ULong amount, ULong transactionId) {
        super(ContractTransferAsset.CONTRACT_TRANSFER_ASSET);

        set(0, id);
        set(1, assetName);
        set(2, ownerId);
        set(3, toId);
        set(4, ownerAddress);
        set(5, toAddress);
        set(6, amount);
        set(7, transactionId);
    }
}
