/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.VoteLive;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VoteLiveRecord extends TableRecordImpl<VoteLiveRecord> implements Record3<String, Long, Integer> {

    private static final long serialVersionUID = -2083168956;

    /**
     * Setter for <code>tmp.vote_live.address</code>.
     */
    public void setAddress(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.vote_live.address</code>.
     */
    public String getAddress() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tmp.vote_live.vote_count</code>.
     */
    public void setVoteCount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.vote_live.vote_count</code>.
     */
    public Long getVoteCount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>tmp.vote_live.position</code>.
     */
    public void setPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.vote_live.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VoteLive.VOTE_LIVE.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return VoteLive.VOTE_LIVE.VOTE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VoteLive.VOTE_LIVE.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVoteCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoteLiveRecord value1(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoteLiveRecord value2(Long value) {
        setVoteCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoteLiveRecord value3(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VoteLiveRecord values(String value1, Long value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteLiveRecord
     */
    public VoteLiveRecord() {
        super(VoteLive.VOTE_LIVE);
    }

    /**
     * Create a detached, initialised VoteLiveRecord
     */
    public VoteLiveRecord(String address, Long voteCount, Integer position) {
        super(VoteLive.VOTE_LIVE);

        set(0, address);
        set(1, voteCount);
        set(2, position);
    }
}
