/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.records;


import io.trxplorer.model.tables.VotingRound;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotingRoundRecord extends UpdatableRecordImpl<VotingRoundRecord> implements Record10<UInteger, UInteger, UInteger, UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp, ULong> {

    private static final long serialVersionUID = -1791912977;

    /**
     * Setter for <code>tmp.voting_round.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>tmp.voting_round.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>tmp.voting_round.day</code>.
     */
    public void setDay(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>tmp.voting_round.day</code>.
     */
    public UInteger getDay() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>tmp.voting_round.month</code>.
     */
    public void setMonth(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>tmp.voting_round.month</code>.
     */
    public UInteger getMonth() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>tmp.voting_round.year</code>.
     */
    public void setYear(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>tmp.voting_round.year</code>.
     */
    public UInteger getYear() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>tmp.voting_round.round</code>.
     */
    public void setRound(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>tmp.voting_round.round</code>.
     */
    public UInteger getRound() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>tmp.voting_round.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tmp.voting_round.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>tmp.voting_round.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tmp.voting_round.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>tmp.voting_round.sync_start</code>.
     */
    public void setSyncStart(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>tmp.voting_round.sync_start</code>.
     */
    public Timestamp getSyncStart() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>tmp.voting_round.sync_end</code>.
     */
    public void setSyncEnd(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>tmp.voting_round.sync_end</code>.
     */
    public Timestamp getSyncEnd() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>tmp.voting_round.vote_count</code>.
     */
    public void setVoteCount(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>tmp.voting_round.vote_count</code>.
     */
    public ULong getVoteCount() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UInteger, UInteger, UInteger, UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp, ULong> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UInteger, UInteger, UInteger, UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp, ULong> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return VotingRound.VOTING_ROUND.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return VotingRound.VOTING_ROUND.DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return VotingRound.VOTING_ROUND.MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return VotingRound.VOTING_ROUND.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return VotingRound.VOTING_ROUND.ROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return VotingRound.VOTING_ROUND.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return VotingRound.VOTING_ROUND.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VotingRound.VOTING_ROUND.SYNC_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return VotingRound.VOTING_ROUND.SYNC_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field10() {
        return VotingRound.VOTING_ROUND.VOTE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getSyncStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getSyncEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value10() {
        return getVoteCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value2(UInteger value) {
        setDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value3(UInteger value) {
        setMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value4(UInteger value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value5(UInteger value) {
        setRound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value6(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value7(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value8(Timestamp value) {
        setSyncStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value9(Timestamp value) {
        setSyncEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord value10(ULong value) {
        setVoteCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VotingRoundRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, UInteger value5, Timestamp value6, Timestamp value7, Timestamp value8, Timestamp value9, ULong value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VotingRoundRecord
     */
    public VotingRoundRecord() {
        super(VotingRound.VOTING_ROUND);
    }

    /**
     * Create a detached, initialised VotingRoundRecord
     */
    public VotingRoundRecord(UInteger id, UInteger day, UInteger month, UInteger year, UInteger round, Timestamp startDate, Timestamp endDate, Timestamp syncStart, Timestamp syncEnd, ULong voteCount) {
        super(VotingRound.VOTING_ROUND);

        set(0, id);
        set(1, day);
        set(2, month);
        set(3, year);
        set(4, round);
        set(5, startDate);
        set(6, endDate);
        set(7, syncStart);
        set(8, syncEnd);
        set(9, voteCount);
    }
}
