ALTER TABLE `chart_transaction` 
DROP COLUMN `date`,
ADD COLUMN `day` SMALLINT UNSIGNED NOT NULL AFTER `id`,
ADD COLUMN `month` SMALLINT UNSIGNED NOT NULL AFTER `day`,
ADD COLUMN `year` SMALLINT UNSIGNED NOT NULL AFTER `month`;
