/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountVote implements Serializable {

    private static final long serialVersionUID = -1769977993;

    private ULong     id;
    private String    voteAddress;
    private ULong     voteAccountId;
    private Long      voteCount;
    private ULong     accountId;
    private Timestamp timestamp;

    public AccountVote() {}

    public AccountVote(AccountVote value) {
        this.id = value.id;
        this.voteAddress = value.voteAddress;
        this.voteAccountId = value.voteAccountId;
        this.voteCount = value.voteCount;
        this.accountId = value.accountId;
        this.timestamp = value.timestamp;
    }

    public AccountVote(
        ULong     id,
        String    voteAddress,
        ULong     voteAccountId,
        Long      voteCount,
        ULong     accountId,
        Timestamp timestamp
    ) {
        this.id = id;
        this.voteAddress = voteAddress;
        this.voteAccountId = voteAccountId;
        this.voteCount = voteCount;
        this.accountId = accountId;
        this.timestamp = timestamp;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getVoteAddress() {
        return this.voteAddress;
    }

    public void setVoteAddress(String voteAddress) {
        this.voteAddress = voteAddress;
    }

    public ULong getVoteAccountId() {
        return this.voteAccountId;
    }

    public void setVoteAccountId(ULong voteAccountId) {
        this.voteAccountId = voteAccountId;
    }

    public Long getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(Long voteCount) {
        this.voteCount = voteCount;
    }

    public ULong getAccountId() {
        return this.accountId;
    }

    public void setAccountId(ULong accountId) {
        this.accountId = accountId;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountVote (");

        sb.append(id);
        sb.append(", ").append(voteAddress);
        sb.append(", ").append(voteAccountId);
        sb.append(", ").append(voteCount);
        sb.append(", ").append(accountId);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }
}
