/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountAsset implements Serializable {

    private static final long serialVersionUID = -720107417;

    private ULong  id;
    private String assetName;
    private ULong  balance;
    private ULong  accountId;

    public AccountAsset() {}

    public AccountAsset(AccountAsset value) {
        this.id = value.id;
        this.assetName = value.assetName;
        this.balance = value.balance;
        this.accountId = value.accountId;
    }

    public AccountAsset(
        ULong  id,
        String assetName,
        ULong  balance,
        ULong  accountId
    ) {
        this.id = id;
        this.assetName = assetName;
        this.balance = balance;
        this.accountId = accountId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    public ULong getBalance() {
        return this.balance;
    }

    public void setBalance(ULong balance) {
        this.balance = balance;
    }

    public ULong getAccountId() {
        return this.accountId;
    }

    public void setAccountId(ULong accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountAsset (");

        sb.append(id);
        sb.append(", ").append(assetName);
        sb.append(", ").append(balance);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
