/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractVoteWitnessVote implements Serializable {

    private static final long serialVersionUID = 984525546;

    private ULong  id;
    private ULong  ownerId;
    private String ownerAddress;
    private ULong  voteCount;
    private ULong  voteWitnessId;

    public ContractVoteWitnessVote() {}

    public ContractVoteWitnessVote(ContractVoteWitnessVote value) {
        this.id = value.id;
        this.ownerId = value.ownerId;
        this.ownerAddress = value.ownerAddress;
        this.voteCount = value.voteCount;
        this.voteWitnessId = value.voteWitnessId;
    }

    public ContractVoteWitnessVote(
        ULong  id,
        ULong  ownerId,
        String ownerAddress,
        ULong  voteCount,
        ULong  voteWitnessId
    ) {
        this.id = id;
        this.ownerId = ownerId;
        this.ownerAddress = ownerAddress;
        this.voteCount = voteCount;
        this.voteWitnessId = voteWitnessId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public ULong getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(ULong ownerId) {
        this.ownerId = ownerId;
    }

    public String getOwnerAddress() {
        return this.ownerAddress;
    }

    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
    }

    public ULong getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(ULong voteCount) {
        this.voteCount = voteCount;
    }

    public ULong getVoteWitnessId() {
        return this.voteWitnessId;
    }

    public void setVoteWitnessId(ULong voteWitnessId) {
        this.voteWitnessId = voteWitnessId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractVoteWitnessVote (");

        sb.append(id);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(ownerAddress);
        sb.append(", ").append(voteCount);
        sb.append(", ").append(voteWitnessId);

        sb.append(")");
        return sb.toString();
    }
}
