/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractWitnessUpdate implements Serializable {

    private static final long serialVersionUID = -119811144;

    private ULong  id;
    private String updateUrl;
    private ULong  ownerId;
    private String ownerAddress;
    private ULong  transactionId;

    public ContractWitnessUpdate() {}

    public ContractWitnessUpdate(ContractWitnessUpdate value) {
        this.id = value.id;
        this.updateUrl = value.updateUrl;
        this.ownerId = value.ownerId;
        this.ownerAddress = value.ownerAddress;
        this.transactionId = value.transactionId;
    }

    public ContractWitnessUpdate(
        ULong  id,
        String updateUrl,
        ULong  ownerId,
        String ownerAddress,
        ULong  transactionId
    ) {
        this.id = id;
        this.updateUrl = updateUrl;
        this.ownerId = ownerId;
        this.ownerAddress = ownerAddress;
        this.transactionId = transactionId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getUpdateUrl() {
        return this.updateUrl;
    }

    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl;
    }

    public ULong getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(ULong ownerId) {
        this.ownerId = ownerId;
    }

    public String getOwnerAddress() {
        return this.ownerAddress;
    }

    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
    }

    public ULong getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(ULong transactionId) {
        this.transactionId = transactionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractWitnessUpdate (");

        sb.append(id);
        sb.append(", ").append(updateUrl);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(ownerAddress);
        sb.append(", ").append(transactionId);

        sb.append(")");
        return sb.toString();
    }
}
