/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractTransferAsset implements Serializable {

    private static final long serialVersionUID = -1525447948;

    private ULong  id;
    private String assetName;
    private ULong  ownerId;
    private ULong  toId;
    private String ownerAddress;
    private String toAddress;
    private ULong  amount;
    private ULong  transactionId;

    public ContractTransferAsset() {}

    public ContractTransferAsset(ContractTransferAsset value) {
        this.id = value.id;
        this.assetName = value.assetName;
        this.ownerId = value.ownerId;
        this.toId = value.toId;
        this.ownerAddress = value.ownerAddress;
        this.toAddress = value.toAddress;
        this.amount = value.amount;
        this.transactionId = value.transactionId;
    }

    public ContractTransferAsset(
        ULong  id,
        String assetName,
        ULong  ownerId,
        ULong  toId,
        String ownerAddress,
        String toAddress,
        ULong  amount,
        ULong  transactionId
    ) {
        this.id = id;
        this.assetName = assetName;
        this.ownerId = ownerId;
        this.toId = toId;
        this.ownerAddress = ownerAddress;
        this.toAddress = toAddress;
        this.amount = amount;
        this.transactionId = transactionId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getAssetName() {
        return this.assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    public ULong getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(ULong ownerId) {
        this.ownerId = ownerId;
    }

    public ULong getToId() {
        return this.toId;
    }

    public void setToId(ULong toId) {
        this.toId = toId;
    }

    public String getOwnerAddress() {
        return this.ownerAddress;
    }

    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
    }

    public String getToAddress() {
        return this.toAddress;
    }

    public void setToAddress(String toAddress) {
        this.toAddress = toAddress;
    }

    public ULong getAmount() {
        return this.amount;
    }

    public void setAmount(ULong amount) {
        this.amount = amount;
    }

    public ULong getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(ULong transactionId) {
        this.transactionId = transactionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractTransferAsset (");

        sb.append(id);
        sb.append(", ").append(assetName);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(toId);
        sb.append(", ").append(ownerAddress);
        sb.append(", ").append(toAddress);
        sb.append(", ").append(amount);
        sb.append(", ").append(transactionId);

        sb.append(")");
        return sb.toString();
    }
}
