/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractAccountCreate implements Serializable {

    private static final long serialVersionUID = 202722290;

    private ULong  id;
    private String accountName;
    private ULong  ownerId;
    private ULong  transactionId;
    private String ownerAddress;

    public ContractAccountCreate() {}

    public ContractAccountCreate(ContractAccountCreate value) {
        this.id = value.id;
        this.accountName = value.accountName;
        this.ownerId = value.ownerId;
        this.transactionId = value.transactionId;
        this.ownerAddress = value.ownerAddress;
    }

    public ContractAccountCreate(
        ULong  id,
        String accountName,
        ULong  ownerId,
        ULong  transactionId,
        String ownerAddress
    ) {
        this.id = id;
        this.accountName = accountName;
        this.ownerId = ownerId;
        this.transactionId = transactionId;
        this.ownerAddress = ownerAddress;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public ULong getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(ULong ownerId) {
        this.ownerId = ownerId;
    }

    public ULong getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(ULong transactionId) {
        this.transactionId = transactionId;
    }

    public String getOwnerAddress() {
        return this.ownerAddress;
    }

    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractAccountCreate (");

        sb.append(id);
        sb.append(", ").append(accountName);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(ownerAddress);

        sb.append(")");
        return sb.toString();
    }
}
