/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Node implements Serializable {

    private static final long serialVersionUID = 92631519;

    private ULong      id;
    private String     host;
    private Integer    port;
    private Byte       up;
    private BigDecimal longitude;
    private BigDecimal latitude;
    private String     countryCode;
    private String     country;
    private String     city;
    private Timestamp  lastUpdated;
    private Timestamp  dateCreated;

    public Node() {}

    public Node(Node value) {
        this.id = value.id;
        this.host = value.host;
        this.port = value.port;
        this.up = value.up;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.countryCode = value.countryCode;
        this.country = value.country;
        this.city = value.city;
        this.lastUpdated = value.lastUpdated;
        this.dateCreated = value.dateCreated;
    }

    public Node(
        ULong      id,
        String     host,
        Integer    port,
        Byte       up,
        BigDecimal longitude,
        BigDecimal latitude,
        String     countryCode,
        String     country,
        String     city,
        Timestamp  lastUpdated,
        Timestamp  dateCreated
    ) {
        this.id = id;
        this.host = host;
        this.port = port;
        this.up = up;
        this.longitude = longitude;
        this.latitude = latitude;
        this.countryCode = countryCode;
        this.country = country;
        this.city = city;
        this.lastUpdated = lastUpdated;
        this.dateCreated = dateCreated;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public Integer getPort() {
        return this.port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public Byte getUp() {
        return this.up;
    }

    public void setUp(Byte up) {
        this.up = up;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Timestamp getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Timestamp lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Node (");

        sb.append(id);
        sb.append(", ").append(host);
        sb.append(", ").append(port);
        sb.append(", ").append(up);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(country);
        sb.append(", ").append(city);
        sb.append(", ").append(lastUpdated);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
