/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transfer implements Serializable {

    private static final long serialVersionUID = 1290427279;

    private ULong     id;
    private String    from;
    private String    to;
    private ULong     amount;
    private String    token;
    private Timestamp timestamp;
    private ULong     transactionId;

    public Transfer() {}

    public Transfer(Transfer value) {
        this.id = value.id;
        this.from = value.from;
        this.to = value.to;
        this.amount = value.amount;
        this.token = value.token;
        this.timestamp = value.timestamp;
        this.transactionId = value.transactionId;
    }

    public Transfer(
        ULong     id,
        String    from,
        String    to,
        ULong     amount,
        String    token,
        Timestamp timestamp,
        ULong     transactionId
    ) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.amount = amount;
        this.token = token;
        this.timestamp = timestamp;
        this.transactionId = transactionId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getFrom() {
        return this.from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return this.to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public ULong getAmount() {
        return this.amount;
    }

    public void setAmount(ULong amount) {
        this.amount = amount;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public ULong getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(ULong transactionId) {
        this.transactionId = transactionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transfer (");

        sb.append(id);
        sb.append(", ").append(from);
        sb.append(", ").append(to);
        sb.append(", ").append(amount);
        sb.append(", ").append(token);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(transactionId);

        sb.append(")");
        return sb.toString();
    }
}
