/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction implements Serializable {

    private static final long serialVersionUID = -496756712;

    private ULong     id;
    private String    hash;
    private Timestamp timestamp;
    private Timestamp expiration;
    private Byte      confirmed;
    private ULong     blockId;
    private String    from;
    private Integer   type;

    public Transaction() {}

    public Transaction(Transaction value) {
        this.id = value.id;
        this.hash = value.hash;
        this.timestamp = value.timestamp;
        this.expiration = value.expiration;
        this.confirmed = value.confirmed;
        this.blockId = value.blockId;
        this.from = value.from;
        this.type = value.type;
    }

    public Transaction(
        ULong     id,
        String    hash,
        Timestamp timestamp,
        Timestamp expiration,
        Byte      confirmed,
        ULong     blockId,
        String    from,
        Integer   type
    ) {
        this.id = id;
        this.hash = hash;
        this.timestamp = timestamp;
        this.expiration = expiration;
        this.confirmed = confirmed;
        this.blockId = blockId;
        this.from = from;
        this.type = type;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public Timestamp getExpiration() {
        return this.expiration;
    }

    public void setExpiration(Timestamp expiration) {
        this.expiration = expiration;
    }

    public Byte getConfirmed() {
        return this.confirmed;
    }

    public void setConfirmed(Byte confirmed) {
        this.confirmed = confirmed;
    }

    public ULong getBlockId() {
        return this.blockId;
    }

    public void setBlockId(ULong blockId) {
        this.blockId = blockId;
    }

    public String getFrom() {
        return this.from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transaction (");

        sb.append(id);
        sb.append(", ").append(hash);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(expiration);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(blockId);
        sb.append(", ").append(from);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
