/*
 * This file is generated by jOOQ.
*/
package io.trxplorer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VoteLive implements Serializable {

    private static final long serialVersionUID = 1451403348;

    private String  address;
    private Long    voteCount;
    private Integer position;

    public VoteLive() {}

    public VoteLive(VoteLive value) {
        this.address = value.address;
        this.voteCount = value.voteCount;
        this.position = value.position;
    }

    public VoteLive(
        String  address,
        Long    voteCount,
        Integer position
    ) {
        this.address = address;
        this.voteCount = voteCount;
        this.position = position;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Long getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(Long voteCount) {
        this.voteCount = voteCount;
    }

    public Integer getPosition() {
        return this.position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VoteLive (");

        sb.append(address);
        sb.append(", ").append(voteCount);
        sb.append(", ").append(position);

        sb.append(")");
        return sb.toString();
    }
}
